$(document).on('ready',function(){var owl=$(".header-slider");owl.owlCarousel({autoPlay:10000,items:1,itemsDesktop:[1920,1],itemsDesktopSmall:[900,1],itemsTablet:[600,1],itemsMobile:[380,1]});$(".next").click(function(){owl.trigger('owl.next');})
$(".prev").click(function(){owl.trigger('owl.prev');})
$(".play").click(function(){owl.trigger('owl.play',3000);})
$(".stop").click(function(){owl.trigger('owl.stop');})
var owl=$(".testimonial");owl.owlCarousel({autoPlay:4000,itemsCustom:[[0,1],[450,1],[600,1],[700,2],[1000,2],[1200,2],[1400,2],[1600,2]]});$(".next").click(function(){owl.trigger('owl.next');})
$(".prev").click(function(){owl.trigger('owl.prev');})
$(".play").click(function(){owl.trigger('owl.play',1000);})
$(".stop").click(function(){owl.trigger('owl.stop');})
var owl=$(".client-logo");owl.owlCarousel({loop:true,responsiveClass:true,center:true,margin:10,smartSpeed:2500,autoPlay:true,autoplayTimeout:5000,lazyLoad:true,itemsCustom:[[0,1],[450,2],[600,3],[700,3],[992,4],[1000,4],[1200,5],[1400,5],[1600,5]]});$(".next").click(function(){owl.trigger('owl.next');})
$(".prev").click(function(){owl.trigger('owl.prev');})
$(".play").click(function(){owl.trigger('owl.play',1000);})
$(".stop").click(function(){owl.trigger('owl.stop');})});$(document).on('ready',function(){var owl=$(".fund-slider");owl.owlCarousel({autoPlay:5000,navigation:true,navigationText:["<div class='icon-left'></div>","<div class='icon-right'></div>"],itemsCustom:[[0,1],[450,2],[600,2],[700,3],[1000,3],[1200,3],[1400,3],[1600,3]]});$(".next").click(function(){owl.trigger('owl.next');})
$(".prev").click(function(){owl.trigger('owl.prev');})
$(".play").click(function(){owl.trigger('owl.play',4500);})
$(".stop").click(function(){owl.trigger('owl.stop');})
var owl=$(".team-carousel");owl.owlCarousel({autoPlay:5000,navigation:true,navigationText:["<div class='left carousel-control'></div>","<div class='right carousel-control'></div>"],itemsCustom:[[0,1],[450,1],[600,1],[700,1],[1000,2],[1200,2],[1400,2],[1600,2]]});$(".next").click(function(){owl.trigger('owl.next');})
$(".prev").click(function(){owl.trigger('owl.prev');})
$(".play").click(function(){owl.trigger('owl.play',4500);})
$(".stop").click(function(){owl.trigger('owl.stop');})});